development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sample_app_development
  pool: 5
  username: root
  password: ENV["DATABASE_PASSWORD"]
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sample_app_test
  pool: 5
  username: root
  password: ENV["DATABASE_PASSWORD"]
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sample_app_production
  pool: 5
  username: root
  password: ENV["DATABASE_PASSWORD"]
  socket: /tmp/mysql.sock
